postgres:
  image: postgres:9.4
  ports:
  - "5432:5432"
  environment:
    POSTGRES_USER: graphql_sequelize_test
    POSTGRES_PASSWORD: graphql_sequelize_test

benchmark_server:
  build: .
  command: [node, test/benchmark.js]
  ports:
  - "4001:4001"
  links:
  - postgres
  volumes:
  - .:/src/graphql-sequelize
  environment:
    DIALECT: postgres
    DB_DATABASE: graphql_sequelize_test
    DB_USER: graphql_sequelize_test
    DB_PASSWORD: graphql_sequelize_test
